/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Frame;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author nishom
 */
public class SPK extends javax.swing.JFrame {

    /**
     * Creates new form SPK
     */
    public SPK() {
        initComponents();

        setLocationRelativeTo(null);
        setExtendedState(Frame.MAXIMIZED_BOTH);
        loadKriteria();
        loadAlternatif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonTrans1 = new app.ButtonTrans();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKriteria = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLaLTERNATIF = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        buttonTrans2 = new app.ButtonTrans();
        buttonTrans3 = new app.ButtonTrans();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilPembobotan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(873, 50));

        buttonTrans1.setText("Tambah Kriteria");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(buttonTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(735, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonTrans1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        tblKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKriteria);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Kriteria", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(873, 50));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        TBLaLTERNATIF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TBLaLTERNATIF);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Alternatif", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(873, 50));

        buttonTrans2.setText("Lakukan Pembobotan (saw)");
        buttonTrans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrans2ActionPerformed(evt);
            }
        });

        buttonTrans3.setText("Lakukan Pembobotan (WP)");
        buttonTrans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrans3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonTrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTrans3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTrans2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(buttonTrans3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        hasilPembobotan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(hasilPembobotan);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Pembobotan", jPanel5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTrans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrans2ActionPerformed
        // TODO add your handling code here:
        SPK_SAW();
        evt.getActionCommand();
    }//GEN-LAST:event_buttonTrans2ActionPerformed

    private void buttonTrans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrans3ActionPerformed
        SPK_WP();
        evt.getActionCommand();
    }//GEN-LAST:event_buttonTrans3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SPK().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBLaLTERNATIF;
    private app.ButtonTrans buttonTrans1;
    private app.ButtonTrans buttonTrans2;
    private app.ButtonTrans buttonTrans3;
    private javax.swing.JTable hasilPembobotan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblKriteria;
    // End of variables declaration//GEN-END:variables

    //Methods for SAW    
    private void loadKriteria() {
        try {
            Object[][] data = null;
            Object[] header = {"ID", "KRITERIA", "BOBOT", "LABEL"};
            DefaultTableModel model = new DefaultTableModel(data, header);
            tblKriteria.setModel(model);

            //load data from DB
            Connection koneksi = Koneksi.konekKeDB();
            Statement st = koneksi.createStatement();
            String query = "SELECT * FROM kriteria";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                int id = rs.getInt("id_kriteria");
                String nama = rs.getString("nama");
                String bobot = rs.getString("bobot");
                String label = rs.getString("label");
                Object[] d = {id, nama, bobot, label};
                model.addRow(d);
            }
        } catch (SQLException e) {

        }
    }

    private void loadAlternatif() {
        try {
            Object[][] data = null;
            Object[] header = {"ID", "NAMA OBAT", "HARGA", "MANFAAT", "ATURAN PAKAI", "DESKRIPSI"};
            DefaultTableModel model = new DefaultTableModel(data, header);
            TBLaLTERNATIF.setModel(model);

            //load data from DB
            Connection koneksi = Koneksi.konekKeDB();
            Statement st = koneksi.createStatement();
            String query = "SELECT * FROM alternatif";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                int id = rs.getInt("id");
                String namaObat = rs.getString("namaObat");
                String harga = rs.getString("harga");
                String manfaat = rs.getString("manfaat");
                String aturanPakai = rs.getString("aturanPakai");
                String deskripsi = rs.getString("deskripsi");

                Object[] d = {id, namaObat, harga, manfaat, aturanPakai, deskripsi};
                model.addRow(d);
            }
        } catch (SQLException e) {

        }
    }

    private void truncate_table(String tableName){
        try {
            Connection c4 = Koneksi.konekKeDB();
            Statement st4 = c4.createStatement();
            String query4 = "TRUNCATE TABLE "+tableName+"";
            st4.executeUpdate(query4);
            st4.close();
        } catch (SQLException e) {
        }
    }
    
    
    private void SPK_SAW() {
        try {
            //List<Double> hasil_saw = new ArrayList<>();
            Object[] header = {"NO", "ALTERNATIF", "BOBOT"};
            Object[][] data = null;
            DefaultTableModel model = new DefaultTableModel(data, header);
            hasilPembobotan.setModel(model);
            int nomor = 0;

            truncate_table("hasil_saw");
            truncate_table("normalisasi");         

            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT * FROM alternatif";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                double id = rs.getDouble("id");
                String nama = rs.getString("namaObat");
                double harga = rs.getDouble("harga");
                double manfaat = rs.getDouble("manfaat");
                double aturanPakai = rs.getDouble("atutanPakai");
                double deskripsi = rs.getDouble("deskripsi");

//                double pembagi_harga = label("harga").equals("cost") ? min("harga") : max("harga");
//                double pembagi_kualitas = label("kualitas").equals("cost") ? min("kualitas") : max("kualitas");
//                double pembagi_fitur = label("fitur").equals("cost") ? min("fitur") : max("fitur");
//                double pembagi_populer = label("populer").equals("cost") ? min("populer") : max("populer");
//                double pembagi_pjual = label("purna_jual").equals("cost") ? min("purna_jual") : max("purna_jual");
//                double pembagi_keawetan = label("keawetan").equals("cost") ? min("keawetan") : max("keawetan");

                double norm_harga = label("harga").equals("cost") ? min("harga") / harga : harga / max("harga");
                double norm_manfaat = label("manfaat").equals("cost") ? min("manfaat") / manfaat : manfaat / max("manfaat");
                double norm_aturanPakai = label("aturanPakai").equals("cost") ? min("aturanPakai") / aturanPakai : aturanPakai / max("aturanPakai");
                double norm_deskripsi = label("deskripsi").equals("cost") ? min("deskripsi") / deskripsi : deskripsi / max("deskripsi");
               

               
                
                Connection c2 = Koneksi.konekKeDB();
                Statement st2 = c2.createStatement();
                String query2 = "INSERT INTO normalisasi"
                        + " (id_alternatif,harga,manfaat,aturanPakai,deskripsi) "
                        + "VALUES "
                        + " ("
                        + "'"+id+"',"
                        + "'"+norm_harga+"',"
                        + "'"+norm_manfaat+"',"
                        + "'"+norm_aturanPakai+"',"
                        + "'"+norm_deskripsi+"',"
                        + ")";
                st2.executeUpdate(query2);
//                System.out.println(bobot("harga"));
//                System.out.println(bobot("kualitas"));
//                System.out.println(bobot("fitur"));
//                System.out.println(bobot("populer"));
//                System.out.println(bobot("purna_jual"));
//                System.out.println(bobot("keawetan"));
                double hasil = (bobot("harga") * norm_harga) + (bobot("manfaat") * norm_manfaat) + (bobot("aturanPakai") * norm_aturanPakai) + (bobot("deskripsi") * norm_deskripsi);
                //hasil_saw.add(hasil);   
                nomor++;

                //String nama_alt = rs.getString("nama");
                Object[] rowData = {nomor, nama, hasil};
                model.addRow(rowData);
                
                
                
                
                Connection c3 = Koneksi.konekKeDB();
                Statement st3 = c3.createStatement();
                String query3 = "INSERT INTO hasil_saw (alternatif,bobot) "
                        + "VALUES "
                        + "('"+nama+"','"+hasil+"')";
                st3.executeUpdate(query3);
            }
            //double max = Collections.max(hasil_saw);
            //System.out.println(max);
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }

    private double min(String kolom) {
        double min = 0;
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT MIN(" + kolom + ") AS min_kolom FROM alternatif";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                min = rs.getDouble("min_kolom");
            }
            return min;

        } catch (SQLException e) {
        }
        return min;
    }

    private double max(String kolom) {
        double max = 0;
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT MAX(" + kolom + ") AS max_kolom FROM alternatif";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                max = rs.getDouble("max_kolom");
            }
            return max;

        } catch (SQLException e) {
        }
        return max;
    }

    private String label(String kolom) {
        String label = "cost";
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT label FROM kriteria WHERE nama='" + kolom + "'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                label = rs.getString("label");
            }
            return label;

        } catch (SQLException e) {
        }
        return label;
    }

    private double bobot(String kolom) {
        double bobot = 0;
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT bobot FROM kriteria WHERE nama='" + kolom + "'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                bobot = rs.getDouble("bobot");
            }
            return bobot;

        } catch (SQLException e) {
        }
        return bobot;
    }

    //Methods for WP    
    private List getVectorS() {
        List<Double> vectorS = new ArrayList<>();
                
        try {
            try (Connection c = Koneksi.konekKeDB()) {
                Statement st = c.createStatement();
                String query = "SELECT * FROM alternatif";
                ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    double harga = rs.getDouble("harga");
                    double manfaat = rs.getDouble("manfaat");
                    double aturanPakai = rs.getDouble("aturanPakai");
                    double deskripsi = rs.getDouble("deskripsi");
                    
                    double pemangkat_harga = label2("harga").equals("benefit") ? bobot2("harga") : -1 * bobot2("harga");
                    double pemangkat_manfaat = label2("manfaat").equals("benefit") ? bobot2("manfaat") : -1 * bobot2("manfaat");
                    double pemangkat_aturanPakai = label2("aturanPakai").equals("benefit") ? bobot2("aturanPakai") : -1 * bobot2("aturanPakai");
                    double pemangkat_deskripsi = label2("deskripsi").equals("benefit") ? bobot2("deskripsi") : -1 * bobot2("deskripsi");
                    
                    
                    double vector_S =
                            Math.pow(harga, pemangkat_harga)*
                            Math.pow(manfaat, pemangkat_manfaat) *
                            Math.pow(aturanPakai, pemangkat_aturanPakai) *
                            Math.pow(deskripsi, pemangkat_deskripsi);
                    vectorS.add(vector_S);
                }
            }
            return vectorS;
        } catch (SQLException e) {
        }
        return vectorS;
    }
    
    public static double getSum(List<Double> nums) {
        double sum = 0;
        for (double i: nums) {
            sum += i;
        }
        return sum;
    }
    
    
    
    private void SPK_WP() {        
        
        try {
            //List<Double> hasil_saw = new ArrayList<>();
            Object[] header = {"NO", "ALTERNATIF", "BOBOT"};
            Object[][] data = null;
            DefaultTableModel model = new DefaultTableModel(data, header);
            hasilPembobotan.setModel(model);
            int nomor = 0;

            try (Connection c = Koneksi.konekKeDB()) {
                Statement st = c.createStatement();
                String query = "SELECT * FROM alternatif";
                ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    int id = rs.getInt("id");
                    String nama = rs.getString("nama");
                    double totalVectorS = getSum(getVectorS());
                    double V = Double.parseDouble(""+getVectorS().get(nomor)) / totalVectorS;
                    nomor++;
                    Object[] dataV = {id,nama,V};
                    model.addRow(dataV);
                }
                //double max = Collections.max(hasil_saw);
                //System.out.println(max);
            }
        } catch (NumberFormatException | SQLException e) {
        }
    }

    private String label2(String kolom) {
        String label = "cost";
        try {
            try (Connection c = Koneksi.konekKeDB()) {
                Statement st = c.createStatement();
                String query = "SELECT label FROM kriteria_wp WHERE nama='" + kolom + "'";
                ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    label = rs.getString("label");
                }
            }
            return label;

        } catch (SQLException e) {
        }
        return label;
    }

    private double bobot2(String kolom) {
        double bobot = 0;
        try {
            try (Connection c = Koneksi.konekKeDB()) {
                Statement st = c.createStatement();
                String query = "SELECT bobot FROM kriteria_wp WHERE nama='" + kolom + "'";
                ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    bobot = rs.getDouble("bobot");
                }
            }
            return bobot;

        } catch (SQLException e) {
        }
        return bobot;
    }

}
